"""audit events

Revision ID: 389bb76836ae
Revises: b327eebbde83
Create Date: 2026-08-20 16:18:45.814022
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '389bb76836ae'
down_revision: str | None = 'b327eebbde83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
